 # NumPy Arrays

In [1]:
import numpy as np

a = np.array([0, 5, 3, 1])
a

array([0, 5, 3, 1])

In [3]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


__Why it is useful:__ Memory-efficient container that provides fast numerical operations.

In [7]:
#Python lists
L = range(1000)
%timeit [i**2 for i in L]

478 µs ± 80.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
#Numpy
a = np.arange(1000)
%timeit a**2

2.36 µs ± 65.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## 1. Creating arrays

__1.1. Manual Construction of arrays__

In [8]:
a = np.array([0, 1, 2, 4])

In [9]:
a

array([0, 1, 2, 4])

In [10]:
a.ndim

1

In [11]:
a.shape

(4,)

In [12]:
len(a)

4

In [13]:
b = np.array([[0, 1, 2], [3, 4, 5]])

b

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
b.ndim

2

In [15]:
b.shape

(2, 3)

In [16]:
len(b)

2

In [17]:
len(b[0])

3

In [18]:
c = np.array([[[0, 1], [2, 3]], [[3, 4], [5, 6]]])

c

array([[[0, 1],
        [2, 3]],

       [[3, 4],
        [5, 6]]])

In [20]:
c.ndim


3

In [21]:
c.shape

(2, 2, 2)

In [23]:
len(c)

2

In [24]:
c[0][0]

array([0, 1])

__1.2. Functions for creating arrays__

In [25]:
a = np.arange(10)

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
b = np.arange(1, 10, 2) #start, end, step

b

array([1, 3, 5, 7, 9])

In [27]:
a = np.linspace(0, 1, 6)  #start, end, number of points

a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [28]:
#common arrays

a = np.ones((3, 3))

a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
b = np.zeros((1,2))

b

array([[0., 0.]])

In [30]:
print(b)

[[0. 0.]]


In [32]:
c = np.eye(3)  #diagonal are ones and else zero

c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
c = np.eye(5)   #5 is number of row and columns

c

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
d = np.eye(3, 2)   #3 is number of rows and 2 is number of columns

d

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [35]:
a = np.diag([3, 5, 1, 7])
    
a

array([[3, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 7]])

In [36]:
np.diag(a)

array([3, 5, 1, 7])

In [37]:
a = np.random.rand(4)

a

array([0.28344382, 0.98687014, 0.52881488, 0.63547682])

In [39]:
b = np.random.rand(4, 2)

b

array([[0.17975893, 0.23110582],
       [0.56773543, 0.82848979],
       [0.64619847, 0.1082982 ],
       [0.29345358, 0.51485473]])

In [41]:
a = np.random.randn(4)

a

array([-1.62829517,  0.73876001, -2.05947142, -0.27722525])

In [42]:
a = np.random.randn(4, 2)

a

array([[-0.79797906, -0.08327907],
       [-0.16685374, -0.26129404],
       [-0.58280779,  0.34473433],
       [-0.88545058, -1.42752101]])

## 2. Basic DataTypes

In [43]:
a = np.arange(10)

a.dtype

dtype('int32')

In [44]:
a = np.arange(10, dtype='float64')

a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [45]:
a.dtype

dtype('float64')

In [46]:
a = np.zeros((3, 3))

print(a)

a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

In [47]:
d = np.array([1+2j, 2+4j])

d.dtype

dtype('complex128')

In [48]:
s = np.array(['ram', 'robert', 'rahim'])

s.dtype

dtype('<U6')

## 3. Indexing ans Slicing

In [49]:
a = np.arange(10)

a[5]

5

In [50]:
a = np.diag([1, 2, 3])

print(a)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [51]:
a[2, 2]

3

In [52]:
a[2, 1] = 5

print(a)

[[1 0 0]
 [0 2 0]
 [0 5 3]]


__3.2 Slicing__

In [54]:
a = np.arange(10)

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
a[1:8:2] # [start: end: step]

array([1, 3, 5, 7])

In [56]:
a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [57]:
b = np.arange(5)

b

array([0, 1, 2, 3, 4])

In [59]:
a[5:] = b[::-1]

a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

## 4. Copies and Views

In [60]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [62]:
np.shares_memory(a, b)

True

In [63]:
b[0] = 10
b

array([10,  2,  4,  6,  8])

In [64]:
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [65]:
a = np.arange(10)

c = a[::2].copy()
c

array([0, 2, 4, 6, 8])

In [66]:
np.shares_memory(a, c)

False

In [68]:
c[0] = 10

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 5. Fancy Indexing 

__Using Boolean Mask__

In [69]:
a = np.random.randint(0, 20, 15)  #start, end, total_required_numbers

a

array([ 9, 13, 17,  2,  0,  8, 11,  3, 19, 12, 15,  3,  7,  0, 16])

In [70]:
mask = (a % 2 == 0)

In [71]:
extract_from_a = a[mask]

extract_from_a

array([ 2,  0,  8, 12,  0, 16])

In [72]:
a[mask] = -1

a

array([ 9, 13, 17, -1, -1, -1, 11,  3, 19, -1, 15,  3,  7, -1, -1])

__Indexing with an array of integers__

In [73]:
a = np.arange(0, 100, 10)

a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [76]:
 b = a[[2, 3, 2, 4, 2]]
    
b

array([20, 30, 20, 40, 20])

In [77]:
a[[9, 7]] = -200

a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])