In [1]:
import numpy as np

# Elementwise operations

### Arithmetic Operations

In [2]:
a = np.array([1, 2, 3, 4])

a

array([1, 2, 3, 4])

In [3]:
a + 2

array([3, 4, 5, 6])

In [4]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

__All arithmetic operates elementwise__

In [5]:
b =np.ones(4) +1

b

array([2., 2., 2., 2.])

In [6]:
a - b

array([-1.,  0.,  1.,  2.])

In [7]:
a * b

array([2., 4., 6., 8.])

In [9]:
c = np.diag([1, 2, 3, 4])

c

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [10]:
#Matrix multiplication
c * c

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 16]])

In [11]:
c.dot(c)

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 16]])

In [12]:
a = np.array([1, 3, 2, 5])
b = np.array([1, 2, 3, 4])

In [13]:
a ==b

array([ True, False, False, False])

In [14]:
a > b

array([False,  True, False,  True])

In [15]:
#array-wise comparisions
np.array_equal(a, b)

False

### Logical Operations

In [18]:
a = np.array([3, 2, 0, 1], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)

np.logical_or(a, b)

array([ True,  True,  True,  True])

In [19]:
np.logical_and(a, b)

array([ True, False, False, False])

### Transcendental functions

In [20]:
a = np.arange(5)

np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [21]:
np.log(a)

C:\Users\LENOVO\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [22]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

### Shape Mismatch

In [23]:
a = np.arange(4)

a + np.array([1, 2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

## Basic Reductions

In [24]:
x = np.array([1, 2, 3, 4])
np.sum(x)

10

In [25]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [26]:
x.sum(axis=0)

array([3, 3])

In [27]:
x.sum(axis=1)

array([2, 4])

In [28]:
x.min()

1

In [29]:
x = np.array([1, 2, 3, 4])

x.min()

1

In [30]:
x.max()

4

In [31]:
x.argmin()   #index of minimum element

0

In [32]:
x.argmax()  #index of maximum element

3

In [33]:
np.all([True, True, False])

False

In [34]:
np.any([True, True, False])

True

In [35]:
a = np.zeros((50, 50))
np.any(a!=0)

False

In [36]:
a[25, 0] = -1


In [39]:
np.any(a!=0)

True

In [40]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

((a <= b) & (b <= c)).all()

True

### Statistics

In [41]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 4, 1]])

In [42]:
x.mean()

1.75

In [43]:
np.median(x)

1.5

In [44]:
np.median(y, axis=-1)

array([2., 4.])

In [45]:
x.std()   #standard diviation

0.82915619758885

In [47]:
y.T

array([[1, 5],
       [2, 4],
       [3, 1]])

## Broadcasting

In [56]:
a = np.tile(np.arange(0, 40, 10), (3, 1))

a

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [57]:
a = a.T
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [58]:
b = np.array([0, 1, 2])
b

array([0, 1, 2])

In [59]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [66]:
a = np.arange(0, 40, 10)
a

array([ 0, 10, 20, 30])

In [67]:
a.shape

(4,)

In [68]:
a = a[:, np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [69]:
a.shape

(4, 1)

In [70]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

 ## Array Shape Manipulation

__Flattening__

In [72]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.ravel()   #return 1-D array

array([1, 2, 3, 4, 5, 6])

In [73]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

__Reshaping__

In [74]:
a.shape

(2, 3)

In [75]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
b = a.ravel()

b

array([1, 2, 3, 4, 5, 6])

In [79]:
b = b.reshape((3, 2))

b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [80]:
b[0, 0] = 200

In [81]:
a

array([[200,   2,   3],
       [  4,   5,   6]])

In [82]:
b

array([[200,   2],
       [  3,   4],
       [  5,   6]])

__Note and Beware: reshape may also return a copy!__

In [83]:
a = np.zeros((3, 2))
b = a.T.reshape(3*2)
b[0] = 50
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

__Adding a Dimension__

In [84]:
z = np.array([1, 2, 3])
z

array([1, 2, 3])

In [86]:
z[:, np.newaxis]

array([[1],
       [2],
       [3]])

__Dimension Shuffling__

In [87]:
a = np.arange(4*3*2).reshape(4,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [88]:
a[0, 2, 1]

5

In [89]:
a[0, 2, 1] = 100

a

array([[[  0,   1],
        [  2,   3],
        [  4, 100]],

       [[  6,   7],
        [  8,   9],
        [ 10,  11]],

       [[ 12,  13],
        [ 14,  15],
        [ 16,  17]],

       [[ 18,  19],
        [ 20,  21],
        [ 22,  23]]])

__Resizing__

In [90]:
a = np.arange(4)
a.resize((8,))
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [91]:
b = a
a.resize((4,))

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

__Sorting Data__

In [92]:
a = np.array([[5, 4, 6], [2, 3, 2]])
b = np.sort(a, axis=1)
b

array([[4, 5, 6],
       [2, 2, 3]])

In [93]:
a.sort(axis=1)
a

array([[4, 5, 6],
       [2, 2, 3]])

In [94]:
#Sorting with fancy indexing
a = np.array([4, 3, 1, 2])
j = np.argsort(a)   #index of sorted element according to array 'a'
j

array([2, 3, 1, 0], dtype=int64)